### ISSUE TITLE
Do nothing for newer vim that supports CurSearch

### ISSUE THREAD

**Issue by idbrii** [PeterRincker/vim-searchlight#10]
This feature is now officially supported in https://github.com/vim/vim/commit/a43993897aa372159f682df37562f159994dc85c and in https://github.com/neovim/neovim/commit/dbc4af71861bf2d3bac6974a0bdb99b18a13666a as a highlight group called `CurSearch`.

Should Searchlight try to disable itself? Unfortunately, `CurSearch` highlight defaults to `Search` which is essentially off by default. And if a user customized `Searchlight` highlight, it wouldn't apply to `CurSearch`.

Something like this might work, but I can't quite get it to apply my Searchlight config (I think because it fires before my colorscheme is loaded):
```
...
highlight default link Searchlight ErrorMsg

if has('patch-8.2.4724') || has('nvim-0.10')
    highlight link CurSearch Searchlight
    finish
endif
```

----
Alternative migration guide: add this to your vimrc *after* you set your `:colorscheme` (replace `Incsearch` with whatever you linked `Searchlight` to):
```
highlight link CurSearch IncSearch
```

Thanks for this great and simple plugin!

**Comment by PeterRincker** [comment]
Thank you for bringing this to my attention. I have updated the plugin with this suggestion
