### ISSUE TITLE
The hightlight is applied only after ~5 seconds

### ISSUE THREAD

**Issue by owd2** [PeterRincker/vim-searchlight#4]
1. Search for something, or press a command like `n` / `N`

Expected: the current term becomes highlighted immediately, and the previous term (if it exists, i.e. if `n` or `N` was used) is no longer highlighted.

Actual: the current term becomes highlighted only after five seconds, and the previous term (if it exists) remains highlighted in that time (the highlight on it gets removed at the same time that the highlight on the current term becomes active).

**Comment by PeterRincker** [comment]
I would like to know your Vim version number and compiled features. Do `:let @+=execute('version')` or `:let @*=execute('version')` to copy `:version` to your clipboard. Are you in the terminal? Working over a slower connection?

Searchlight works primarily by updating the current search highlight when the cursor moves (aka `CursorMoved` autocmd).  It does use a timer with a time of `1ms` to play nice with other `CursorMoved` like plugins like [vim-cool](https://github.com/romainl/vim-cool). Are you using any other plugins which rely on `CursorMoved`?

**Comment by owd2** [comment]
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Jun 06 2019 17:31:41)
Included patches: 1-1453
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +cmdline_hist      +eval              +job               +mouse             +num64             +scrollbind        +termresponse      +windows
+arabic            +cmdline_info      +ex_extra          +jumplist          +mouseshape        +packages          +signs             +textobjects       +writebackup
+autocmd           +comments          +extra_search      +keymap            +mouse_dec         +path_extra        +smartindent       +timers            +X11
-autoservername    +conceal           +farsi             +lambda            +mouse_gpm         +perl              +startuptime       +title             -xfontset
+balloon_eval      +cryptv            +file_in_path      +langmap           -mouse_jsbterm     +persistent_undo   +statusline        +toolbar           +xim
+balloon_eval_term +cscope            +find_in_path      +libcall           +mouse_netterm     +postscript        -sun_workshop      +user_commands     +xpm
+browse            +cursorbind        +float             +linebreak         +mouse_sgr         +printer           +syntax            +vertsplit         +xsmp_interact
++builtin_terms    +cursorshape       +folding           +lispindent        -mouse_sysmouse    +profile           +tag_binary        +virtualedit       +xterm_clipboard
+byte_offset       +dialog_con_gui    -footer            +listcmds          +mouse_urxvt       -python            +tag_old_static    +visual            -xterm_save
+channel           +diff              +fork()            +localmap          +mouse_xterm       +python3           -tag_any_white     +visualextra       
+cindent           +digraphs          +gettext           +lua               +multi_byte        +quickfix          +tcl               +viminfo           
+clientserver      +dnd               -hangul_input      +menu              +multi_lang        +reltime           +termguicolors     +vreplace          
+clipboard         -ebcdic            +iconv             +mksession         -mzscheme          +rightleft         +terminal          +wildignore        
+cmdline_compl     +emacs_tags        +insert_expand     +modify_fname      +netbeans_intg     -ruby              +terminfo          +wildmenu          
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-8l5tlu/vim-8.0.1453=. -fstack-protector-strong -Wformat -Werror=format-security -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.26/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm     
```

I am in the terminal (urxvt) and my internet connection is fine. I do use `vim-cool` but I removed it to test this issue and it's still there regardless. Other than that, Now that you mention `CursorMoved`, I grepped for disabled all plugins which use it, but the issue is still there.
Note that if I 'spam' `n`, the highlight will move immediately, but it will still be on the previous term. And again, if I stop, after ~5s it will fix itself.

 Thank you for your work.

**Comment by PeterRincker** [comment]
I have only tested this on Vim 8.1 and Vim 8.2. Although feature-wise Vim 8.0 should in theory work (in theory). Since you have tested this without plugins then I think it is safe to assume there is no conflict with other plugins.

> Note that if I 'spam' n, the highlight will move immediately, but it will still be on the previous term.

This is very strange as before any current search highlighting is done, the plugin clears the all other previous highlighting. This makes me wonder if there is a screen update issue with your Vim version. I found the following patch:

    Patch 8.0.1476
    Problem:    Screen isn't always updated right away.
    Solution:   Adjust #ifdef: Call out_flush() when not running the GUI.

Can you upgrade Vim to a newer version? Otherwise I think I will have to force a `:redraw` inside of the update function. I would rather avoid needless redraws if possible. Assuming that is the root issue of course.

**Comment by owd2** [comment]
I updated to Vim version 8.2.397 and now it works correctly. Thank you very much!
