### ISSUE TITLE
wrong region is highlighted in nvim for certain search patterns

### ISSUE THREAD

**Issue by jdhao** [PeterRincker/vim-searchlight#6]
I am using nvim 0.5.1 and I found that for certain search patterns, the highlighted region is wrong.

To reproduce, open the following content in a file (`test.txt`):

```
MANDATORY_MANPATH           /usr/man
MANDATORY_MANPATH           /usr/share/man
MANDATORY_MANPATH           /usr/local/share/man
#---------------------------------------------------------
# set up PATH to MANPATH mapping
# ie. what man tree holds man pages for what binary directory.
#
#       *PATH*        ->    *MANPATH*
#
MANPATH_MAP /bin            /usr/share/man
MANPATH_MAP /usr/bin        /usr/share/man
```

Minimal conf:

```
set runtimepath+=/home/jdhao/.local/share/nvim/site/pack/packer/opt/vim-searchlight
```

Then open nvim : `nvim --clean -u mini.vim test.txt`.

Search (`/`) for the following pattern:

```
\v^(#)@!
```

Press `n` to go to the next match. Notice that the highlighted region is not correct, especially when the cursor is on line 3, where line 4 - 9 will also be wrongly highlighted.

**Comment by PeterRincker** [comment]
This issue is occurring with zero-width matches e.g. `/^`. I have fixed this by specifically looking for such cases. It should be noted however, the cursor will cover up a zero-width match so it could be tricky to see the highlighted match without some cursor blink
